swagger: "2.0"
info:
  title: 便于开发的工具集合
  description: nothing to talk.
  version: 1.1.2
  contact:
    email: alloyjetereting@gmail.com
basePath: /api
paths:
  /config/mysql:
    get:
      tags:
      - config
      summary: Mysql 配置
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /docToCode/apiPhoneController:
    put:
      tags:
      - docToCode
      summary: 生成apiphone的controller层
      parameters:
      - in: body
        name: body
        description: 页面名称|名称英文+回车+接口名称|名称英文|参数+参数|i（是否带用户码）
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /docToCode/apiPhoneHandle:
    put:
      tags:
      - docToCode
      summary: 生成apiphone的handle层
      parameters:
      - in: body
        name: body
        description: 页面名称|名称英文+回车+接口名称|名称英文|参数+参数|i（是否带用户码）
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /excelToMysql/getTempTableSql:
    get:
      tags:
      - excelToMysql
      summary: 获取创建temp_table语句
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /excelToMysql/parseFile:
    post:
      tags:
      - excelToMysql
      summary: 上传xlsx文件并解析到临时表
      parameters:
      - in: formData
        name: fileData
        description: 文件数据(只支持xlsx格式的 小于62列) 导入完成后该文件会被自动删除
        required: true
        type: file
      - in: query
        name: mark
        description: 用于区分导入的文件，对应excel_table表的 Mark 字段
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /modelTranslateMarkDown/MarkDownToModel:
    put:
      tags:
      - modelTranslateMarkDown
      summary: markdown to model
      parameters:
      - in: body
        name: body
        description: markdown里面的内容,此接口只支持bson,按照： |属性|类型|字段|备注|  或 |字段|类型|说明|
        required: true
        type: string
      - in: query
        name: description
        description: 备注是否放在描述里面
        type: boolean
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /modelTranslateMarkDown/ModelToMarkDown:
    put:
      tags:
      - modelTranslateMarkDown
      summary: model to markdown
      parameters:
      - in: body
        name: body
        description: 结构体里面的内容,此接口只支持bson,按照： |属性|类型|数据库字段|备注|
        required: true
        type: string
      - in: query
        name: is3
        description: '|字段|类型|说明|'
        type: boolean
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /modelTranslateMarkDown/SchemaToMarkDown:
    put:
      tags:
      - modelTranslateMarkDown
      summary: 科技厅项目 Schema to Markdown |数据库字段|备注|
      parameters:
      - in: body
        name: body
        description: 科技厅结构体里面的内容
        required: true
        type: string
      - in: query
        name: is3
        description: '|数据库字段|类型|备注|'
        type: boolean
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /mysqlToExcel/toExcel:
    put:
      tags:
      - mysqlToExcel
      summary: mysql导出到excel
      parameters:
      - in: body
        name: body
        description: sql内容
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /tabletostruct/tabletostruct:
    put:
      tags:
      - tabletostruct
      summary: mysql表生成结构体
      parameters:
      - in: body
        name: body
        description: mysql 表的创建语句
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /toLowercase/toLowerCase:
    put:
      tags:
      - toLowercase
      summary: 转化为小写
      parameters:
      - in: body
        name: body
        description: 要变成小写的内容
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
tags:
- name: config
  description: |
    配置文件
- name: excelToMysql
  description: |
    excle导入到临时表
- name: mysqlToExcel
  description: |
    导出到excel
- name: modelTranslateMarkDown
  description: |
    model 和 markdown 的相互转化
- name: toLowercase
  description: |
    路由等全部转化成小写
- name: docToCode
  description: |
    文档生成代码
- name: tabletostruct
  description: |
    mysql表生成结构体
