swagger: "2.0"
info:
  title: 便于开发的工具集合
  description: nothing to talk.
  version: 1.0.0
  contact:
    email: alloyjetereting@gmail.com
basePath: /api
paths:
  /excelToMysql/getTempTableSql:
    get:
      tags:
      - excelToMysql
      summary: 获取创建temp_table语句
      operationId: ExcelToMysqlController.获取创建temp_table语句
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
  /excelToMysql/parseFile/:
    post:
      tags:
      - excelToMysql
      summary: 上传xlsx文件并解析到临时表
      operationId: ExcelToMysqlController.上传xlsx文件并解析到临时表
      parameters:
      - in: formData
        name: fileData
        description: 文件数据(暂时只支持xlsx格式的 且只有一个sheet,小于62列) 导入完成后该文件会被自动删除
        required: true
        type: file
      - in: query
        name: mark
        description: 用于区分导入的文件，对应temp_table表的 Mark 字段
        required: true
        type: string
      responses:
        "200":
          description: 成功
        "400":
          description: 请求发生错误
        "500":
          description: 服务器错误
tags:
- name: excelToMysql
  description: |
    excle导入到临时表
